site_name: Hyperledger Composer中文文档
site_url: https://wbwangk.github.io/ComposerDocs/
repo_url: https://github.com/wbwangk/ComposerDocs
site_description: 'Hyperledger Composer中文文档'

site_author: wbwangk
copyright: wbwangk(wbwang@inspur.com)

theme: readthedocs

pages:
    - 欢迎: index.md
    - 介绍: 
      - 介绍: introduction_introduction.md
      - 关键概念: introduction_key-concepts.md
      - 典型解决方案架构: introduction_solution-architecture.md
    - 安装:
      - 本地安装Playground: installing_using-playground-locally.md
      - 安装开发环境: installing_development-tools.md
    - 教程: 
      - 教程: tutorials_tutorials.md
      - Playground教程: tutorials_playground-tutorial.md
      - 开发者教程: tutorials_developer-tutorial.md
      - 查询教程: tutorials_queries.md
      - 为单个组织部署Hyperledger Fabric: tutorials_deploy-to-fabric-single-org.md
      - 为多个组织部署Hyperledger Fabric: tutorials_deploy-to-fabric-multi-org.md
      - 为多个组织部署Hyperledger Fabric(v0.17): tutorials_deploy-to-fabric-multi-org-v0.17.md
    - 使用Playground:
      - 使用Playground: playground_playground-index.md
      - 业务网络卡片: playground_id-cards-playground.md
    - 开发业务网络:
      - 开发业务网络: business-network_business-network-index.md
      - 业务网络定义: business-network_businessnetworkdefinition.md
      - 创建一个业务网络定义: business-network_bnd-create.md
      - 部署业务网络: business-network_bnd-deploy.md
      - 发送事件: business-network_publishing-events.md
      - 测试业务网络: business-network_testing.md
      - 发布模型或业务网络定义: business-network_bnd-publish.md
      - 查询和过滤业务网络数据: business-network_query.md
      - 可编程访问控制: business-network_programmatic-access-control.md
      - Hyperledger Composer历史库: business-network_historian.md
    - 开发应用程序:
      - 开发应用程序: applications_applications-index.md
      - 编写Node.js应用程序: applications_node.md
      - 编写Web或移动应用: applications_web.md
      - 订阅事件: applications_subscribing-to-events.md
    - 集成现有系统: 
      - 集成现有系统: integrating_integrating-index.md
      - 生成REST API: integrating_getting-started-rest-api.md
      - 从REST服务器发布事件: integrating_publishing-events.md
      - 为REST服务器启用身份认证: integrating_enabling-rest-authentication.md
      - 为REST服务器启用多用户模式: integrating_enabling-multiuser.md
      - 使用HTTPS和TLS来保护REST服务器: integrating_securing-the-rest-server.md
      - 为业务网络部署REST服务器: integrating_deploying-the-rest-server.md
      - 与Node-RED集成: integrating_node-red.md
      - 调用外部REST服务: integrating_call-out.md
    - 管理已部署业务网络: 
      - 管理已部署业务网络: managing_managingindex.md
      - 参与者和身份: managing_participantsandidentities.md
      - 增加参与者: managing_participant-add.md
      - 创建、导出和导入业务网络卡片: managing_id-cards-playground.md
      - 向参与者发放新的身份: managing_identity-issue.md
      - 将现有身份绑定到参与者: managing_identity-bind.md
      - 列出业务网络中的所有身份: managing_identity-list.md
      - 撤销参与者的身份: managing_identity-revoke.md
      - 更新Hyperledger Composer运行时: managing_updating-composer.md
    - 诊断问题: problems_diagnostics.md
    - 参考:
      - 参考: reference-index.md
      - Hyperledger Composer npm模块: reference_MeetTheModules.md
      - 建模语言: reference_cto_language.md
      - 访问控制语言: reference_acl_language.md
      - 查询语言: reference_query-language.md
      - 模型兼容性: reference_model-compatibility.md
      - 连接配置文件: reference_connectionprofile.md
      - 交易处理器函数: reference_js_scripts.md
      - Hyperledger Composer命令行: 
        - reference_commands.md
        - reference/composer.archive.create.md
        - reference/composer.archive.list.md
        - reference/composer.card.create.md
        - reference/composer.card.delete.md
        - reference/composer.card.export.md
        - reference/composer.card.import.md
        - reference/composer.card.list.md
        - reference/composer.identity.bind.md
        - reference/composer.identity.issue.md
        - reference/composer.identity.list.md
        - reference/composer.identity.request.md
        - reference/composer.identity.revoke.md
        - reference/composer.network.deploy.md
        - reference/composer.network.list.md
        - reference/composer.network.logLevel.md
        - reference/composer.network.ping.md
        - reference/composer.network.start.md
        - reference/composer.network.undeploy.md
        - reference/composer.network.update.md
        - reference/composer.network.upgrade.md
        - reference/composer.participant.add.md
        - reference/composer.runtime.install.md
        - reference/composer.transaction.submit.md
      - Hyperledger Composer REST服务器: reference_rest-server.md
      - Hyperledger Composer术语: reference_glossary.md
    - API参考:
      - API参考: api/api-doc-index.md

markdown_extensions:
  - extra
  - tables
  - toc:
      permalink: True
  - fenced_code
  - smarty
  - mdx_math:
      enable_dollar_delimiter: True
  - footnotes
