site_name: Hyperledger Composer中文文档
site_url: https://wbwangk.github.io/ComposerDocs/
repo_url: https://github.com/wbwangk/ComposerDocs
site_description: 'Hyperledger Composer中文文档'

site_author: wbwangk
copyright: wbwangk(wbwang@inspur.com)

theme: readthedocs

pages:
    - 介绍: 
      - 介绍: introduction_introduction.md
      - 关键概念: introduction_key-concepts.md
      - 典型解决方案架构: introduction_solution-architecture.md
    - 安装:
      - 安装开发环境: installing_development-tools.md
    - 教程: 
      - 教程: tutorials_tutorials.md
      - Playground教程: tutorials_playground-tutorial.md
      - 开发者教程: tutorials_developer-tutorial.md
      - 查询教程: tutorials_queries.md
      - 为单个组织部署Hyperledger Fabric: tutorials_deploy-to-fabric-single-org.md
      - 为多个组织部署Hyperledger Fabric: tutorials_deploy-to-fabric-multi-org.md
    - 集成现有系统: 
      - 集成现有系统: integrating_integrating-index.md
      - 生成REST API: integrating_getting-started-rest-api.md
      - 从REST服务器发布事件: integrating_publishing-events.md
      - 为REST服务器启用身份认证: integrating_enabling-rest-authentication.md
      - 为REST服务器启用多用户模式: integrating_enabling-multiuser.md
      - 使用HTTPS和TLS来保护REST服务器: integrating_securing-the-rest-server.md
      - 为业务网络部署REST服务器: integrating_deploying-the-rest-server.md
      - 与Node-RED集成: integrating_node-red.md
      - 调用外部REST服务: integrating_call-out.md
    - 管理已部署业务网络: 
      - 管理已部署业务网络: managing_managingindex.md
      - 参与者和身份: managing_participantsandidentities.md
      - 增加参与者: managing_participant-add.md
      - 创建、导出和导入业务网络卡片: managing_id-cards-playground.md
      - 向参与者发放新的身份: managing_identity-issue.md
      - 将现有身份绑定到参与者: managing_identity-bind.md
      - 列出业务网络中的所有身份: managing_identity-list.md
      - 撤销参与者的身份: managing_identity-revoke.md
      - 更新Hyperledger Composer运行时: managing_updating-composer.md
    - 诊断问题: problems_diagnostics.md
    - 参考:
      - 参考: reference-index.md
      - 建模语言: reference_cto_language.md
      - 查询语言: reference_query-language.md
      - 连接配置文件: reference_connectionprofile.md
      - 交易处理器函数: reference_js_scripts.md
      - Hyperledger Composer命令行: reference_commands.md
      - Hyperledger Composer REST服务器: reference_rest-server.md
      - Hyperledger Composer术语: reference_glossary.md

markdown_extensions:
  - extra
  - tables
  - toc:
      permalink: True
  - fenced_code
  - smarty
  - mdx_math:
      enable_dollar_delimiter: True
  - footnotes
